project:
  type: website
  output-dir: docs

website:
  title: "Anna Ly's Personal Website"
  navbar:
    right:
      - href: pages/index.qmd
        text: "Home"
      - pages/about.qmd
      - pages/cv.qmd
      - text: "Random Notes"
        menu:
          - href: pages/notes/mathematical_stats.qmd
            text: "Mathematial Statistics"
      - text: "Advice"
        menu: 
          - href: pages/advice/advice_grad.qmd
            text: "Graduate School Admissions"
          - href: pages/advice/advice_undergrad.qmd
            text: "Succeeding in Undergrad"
      - text: "Teaching"
        menu: 
          - href: pages/teaching/sta304.qmd
            text: "STA304 Project Resources"
          - href: pages/teaching/sta260summer2024.qmd
            text: "STA260 Summer 2024"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

