project:
  type: website
  output-dir: docs

website:
  title: "Anna Ly"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - text: "Teaching"
        menu: 
          - href: sta.qmd
            text: "STA260 Summer 2024"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

