project:
  type: website
  output-dir: docs

website:
  title: "Anna Ly's Personal Website"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - cv.qmd
      - text: "Advice"
        menu: 
          - href: advice_grad.qmd
            text: "Graduate School"
      - text: "Teaching"
        menu: 
          - href: sta304.qmd
            text: "STA304 Project Resources"
          - href: sta260summer2024.qmd
            text: "STA260 Summer 2024"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

