project:
  type: website
  output-dir: docs

website:
  title: "Anna Ly's Personal Website"
  navbar:
    right:
      - href: pages/index.qmd
        text: "Home"
      - pages/about.qmd
      - text: "Curriculum Vitae"
        menu: 
        - href: pages/cv/edu_exp.qmd
          text: "Education & Experience"
        - href: pages/cv/publications.qmd
          text: "Publications & Conferences"
        - href: pages/cv/scholarships.qmd
          text: "Scholarships & Awards"
      - text: "Teaching"
        menu: 
          - href: pages/teaching/sta304.qmd
            text: "STA304 Project Resources"
          - href: pages/teaching/stats2d03fall2024.qmd
            text: "STATS 2D03 Fall 2024"
          - href: pages/teaching/sta260summer2024.qmd
            text: "STA260 Summer 2024"
          - href: pages/teaching/math1aa3_1zb3winter2025.qmd
            text: "MATH 1AA3 / 1ZB3 Winter 2025"
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

