---
title: "Curriculum Vitae"
toc: true
toc-depth: 3 # This sets the depth of headers included in the TOC
toc-location: left
toc-collapsible: true
---

## Education

**McMaster University ✦ M.Sc in Statistics.** (September 2024 - Present)

**University of Toronto ✦ H.B.Sc in Applied Statistics & Mathematics.** (September 2019 - June 2024)

## Experience

### **Department of Mathematics & Statistics, McMaster**

**Teaching Assistant ✦ September 2024 - TBA**

I am a teaching assistant for [STATS 2D03](https://academiccalendars.romcmaster.ca/preview_course_nopop.php?catoid=53&coid=266605) - Introduction to Probability for the Fall 2024 term!

### **Department of Statistical Sciences, University of Toronto**

**Research Assistant ✦ November 2022 - August 2024**

Under the direction of [Mike Evans](https://utstat.toronto.edu/mikevans/), I spearheaded development of a full-stack R Shiny web application for relative belief inferences to be used by statistical researchers. You may view some of my work [here](https://www.utstat.utoronto.ca/mikevans/relativebeliefcode.html).

### Epson Canada

**Data & Evaluation Specialist** **✦ May 2022 - August 2023**

I performed data capturing and annotation, analyzed results, and provided visualization/graphs for the research team. Furthermore, I worked on Python software development and refactoring and wrote appropriate evaluation process documentation. Moreover, I aided in researching robotic hardware platforms to evaluate the performance of machine learning algorithms, such as differentiable rendering, XAI, and representation learning.

Teams were being restructured and I spent the remaining of my internship performing business analysis tasks. I conducted market research to uncover optimal product applications across industries, survey design & deployment, constructed SWOT analysis reports, and developed predictive financial models in Excel VBA for COGS forecasting, enabling accurate & rapid cost analysis of 3D computer vision solutions for management.

### Department of Mathematical and Computational Sciences, University of Toronto

**Teaching Assistant ✦ July 2021 - August 2024**

I prepared and ran discussion-based and skill-development tutorials to at least 200 students, graded assessments for over 1000 students, hosted scheduled office hours, invigilated tests/exams, and answered students' questions on a classroom forum hosted on Piazza. I independently facilitated and managed large-scale final course projects for Sampling & Survey Design and Experimental Design.

In fact, I mostly created this website to post some of my useful tutorial notes. I believe it will help students in the future.

All of my appointments:

-   [MAT136H5](https://utm.calendar.utoronto.ca/course/mat136h5): Integral Calculus (Winter 2022)

-   [STA107H5](https://utm.calendar.utoronto.ca/course/sta107h5): An Introduction to Probability and Modelling (Winter 2022)

-   [STA256H5](https://utm.calendar.utoronto.ca/course/sta256h5): Probability & Statistics I (Summer 2021, Fall 2021)

-   [STA258H5](https://utm.calendar.utoronto.ca/course/sta258h5): Statistics with Applied Probability (Winter 2022)

-   [STA260H5](https://utm.calendar.utoronto.ca/course/sta260h5): Probability & Statistics II (Winter 2022, Fall 2023, Summer 2024)

-   [STA304H5](https://utm.calendar.utoronto.ca/course/sta304h5): Sampling & Survey Design (Fall 2022, Fall 2023)

-   [STA305H5](https://utm.calendar.utoronto.ca/course/sta305h5): Experimental Design (Winter 2023, Winter 2024)

-   [Math Circles](https://www.utm.utoronto.ca/math-cs-stats/outreach/math-circles): After-School Program for Secondary Students (Winter 2022, Fall 2023)

**Research Assistant**

I've had multiple contracts as a research assistant for computer science researchers and statistics researchers. Below are some of the dates I've worked, as well as a brief description of what I completed.

-   **(Computer Science Education) September 2020 - August 2021**

    -   Under the guidance of [Andrew Petersen](https://utmandrew.bitbucket.io/), I aided in deploying surveys via Qualtrics, refining responses for Python/R graphs (line charts, box plots, bar plots, histograms, correlation matrices) for researchers' insights. I also computed and reported statistics (Python/R) to bolster research paper development, and assisted in writing four published journal articles.

-   **(Computer Science Education) April 2023 - August 2023, April 2024 - August 2024**

    -   Working under the supervision of [Tingting Zhu](https://sites.utm.utoronto.ca/tzhu/content/tingting-zhu), I performed quantitative analysis on survey data to understand whether different types of videos improve students' learning. Additionally, I analyzed Youtube analytics to understand audience retention.

-   **(Statistical Education)** **April 2024 - August 2024**

    -   Advised by [Luai Al Labadi](https://www.utm.utoronto.ca/math-cs-stats/people/luai-al-labadi), I preformed quantitative analysis on survey data to understand the impact of incorporating projects into statistical courses, specifically for the courses [Surveys, Sampling and Observational Data](https://utm.calendar.utoronto.ca/course/sta304h5) and [Experimental Design](https://utm.calendar.utoronto.ca/course/sta305h5). We also researched suggestions for implementing projects that will be incorporated in the Fall 2024 - Winter 2025 academic year.

## Skills

-   Programming Languages: R, Python, SAS, HTML/CSS, Excel VBA

-   R Libraries: Shiny, Tidyverse (Ggplot2, Dplyr, Stringr), Markdown

-   Python Libraries: Matplotlib, NumPy, Pandas, SciPy, Seaborn, Plotly, OpenCV, Pillow, Pytorch, Albumentations

-   Quarto, PostgreSQL, Git, LaTeX, Qualtrics, Microsoft 365 (Word, Excel, PowerPoint, Power Bi), Google Drive

## Publications

**8. A Short Note on Generating a Random Sample from Finite Mixture Distributions**

-   Authors: Luai Al Labadi, Anna Ly

-   Axioms 2023 ✦ Volume 13 (5), Page 307 ✦ <https://doi.org/10.3390/axioms13050307>

**7. Evaluating Storytelling Videos Using YouTube Analytics**

-   Authors: Anna Ly, Tingting Zhu, Andrew Petersen

-   SIGCSE 2024: Proceedings of the 55th ACM Technical Symposium on Computer Science Education V. 2 ✦ Pages 1730 - 1731 ✦ <https://doi.org/10.1145/3626253.3635503>

**6. "I Didn't Know": Examining Student Understanding of Academic Dishonesty in Computer Science**

-   Authors: Michael Liut, Anna Ly, Jessica Jia-Ni Xu, Justice Banson, Paul Vrbik, Caroline D Hardin

-   SIGCSE 2024: Proceedings of the 55th ACM Technical Symposium on Computer Science Education V. 1 ✦ Pages 757 - 763 ✦ <https://doi.org/10.1145/3626252.3630753>

**5. Bayesian Estimation of Variance-Based Information Measures and Their Application to Testing Uniformity**

-   Authors: Luai Al-Labadi, Mohammed Hamlili, Anna Ly

-   Axioms 2023 ✦ Volume 12 (9), Page 887 ✦ <https://doi.org/10.3390/axioms12090887>

**4. "I Am Not Enough": Impostor Phenomenon Experiences of University Students**

-   Authors: Angela Zavaleta Bernuy, Anna Ly, Brian Harrington, Michael Liut, Sadia Sharmin, Lisa Zhang, Andrew Petersen

-   ITiCSE 2023: Proceedings of the 2023 Conference on Innovation and Technology in Computer Science Education V. 1 ✦ Pages 313 - 319 ✦ <https://doi.org/10.1145/3587102.3588779>

**3. Additional Evidence for the Prevalence of the Impostor Phenomenon in Computing**

-   Authors: Angela Zavaleta Bernuy, Anna Ly, Brian Harrington, Michael Liut, Andrew Petersen, Sadia Sharmin, Lisa Zhang

-   SIGCSE 2022: Proceedings of the 53rd ACM Technical Symposium on Computer Science Education - Volume 1 ✦ Pages 654 - 660 ✦ <https://doi.org/10.1145/3478431.3499282>

**2. Spatial Skills and Demographic Factors in CS1**

-   Authors: Anna Ly, Jack Parkinson, Quintin Cutts, Michael Liut, Andrew Petersen

-   Koli Calling '21: Proceedings of the 21st Koli Calling International Conference on Computing Education Research ✦ Article No.: 4, Pages 1 - 10 ✦ <https://doi.org/10.1145/3488042.3488049>

**1. Revisiting syntax exercises in CS1**

-   Authors: Anna Ly, John Edwards, Michael Liut, Andrew Petersen

-   SIGITE '21: Proceedings of the 22nd Annual Conference on Information Technology Education ✦ Pages 9 - 14 ✦ <https://doi.org/10.1145/3450329.3476855>

## Conferences

**2. Joint Statistical Meetings (JSM) - Aug 2023**

Panelist: Pedagogical Perspectives on Teaching and Communiating Statistical Sciences Through the Arts

**1. International Association for Statistical Education (IASE) - July 2023**

Poster Presenter: [Thinking Beyond Numbers - Statistical Perceptions of Communicating Statistics Through the Arts](https://iase-web.org/Webinars.php?p=230711_2000)

## Scholarships & Awards

**9. [Milos Novotny Fellowship](https://gs.mcmaster.ca/program/mathematics/#nav-scholarships) - McMaster University (2024)**

Established through the generosity of Dr. M. Novotny, PhD in Mathematics (McMaster, 1972), this fellowship supports promising graduate students in analysis.

**8. [Ontario Graduate Scholarship (OGS)](https://osap.gov.on.ca/OSAPPortal/en/A-ZListofAid/PRDR019245.html) - McMaster University (2024)**

The Ontario Graduate Scholarship (OGS) programs provide funding to full-time students at the master’s and doctoral levels with an A- or above average, and are hand-selected from the department.

**7. [NSERC Undergraduate Student Research Awards (USRA)](https://www.utm.utoronto.ca/math-cs-stats/news/2023-mcs-awards-ceremony-and-winners-congratulations) - University of Toronto (2023)**

A scholarship which allows students to obtain valuable research experience to encourage students to consider graduate studies and pursue careers in the natural sciences and engineering.

Paper: [Bayesian Estimation of Variance-Based Information Measures and Their Application to Testing Uniformity](https://www.mdpi.com/2075-1680/12/9/887)

**6. [UTM Undergraduate Research Grant](https://www.utm.utoronto.ca/dean/awards-grants/undergraduate-awards-grants/utm-undergraduate-research-grants) - University of Toronto (2022)**

These grants are provided for undergraduate student-initiated research projects supervised by UTM faculty members.

-   Paper 1: [A Short Note on Generating a Random Sample from Finite Mixture Distributions](https://www.mdpi.com/2075-1680/13/5/307)

-   Paper 2: TBA...

**5.** [**Dean’s List Scholar**](https://artsci.calendar.utoronto.ca/academic-record#recog-acad-achievement) **- University of Toronto (2020, 2021, 2022)**

Conferred only on students who have achieved a cumulative grade point average of 3.50 at the end of each session in which the fifth, tenth, fifteenth or twentieth course has been passed at the University of Toronto.

**4. Mathematical and Computational Sciences Honor Roll - University of Toronto (2021, 2022)**

Awarded to students for achieving A+ for multiple mathematical sciences courses at the University of Toronto. I achieved at least five A+ grades in [2021](https://www.utm.utoronto.ca/math-cs-stats/awards/honour-roll/2020-2021) and in [2022](https://www.utm.utoronto.ca/math-cs-stats/awards/student-awards/honour-roll/2021-2022).

This award was discontinued in the 2022-2023 school year. I did get A+ in 5 mathematical sciences courses in the 2023-2024 academic year though. ;)

**3. [President's Scholars of Excellence Scholarship](https://future.utoronto.ca/scholarships/presidents-scholars-of-excellence-program/) - University of Toronto (2019)**

Awarded to 150 most qualified students applying to first year of direct-entry at the University of Toronto.

**2. Governor General’s Academic Bronze Medal - Saint Michael's Catholic High School (2019)**

Awarded to the student who achieves the highest average in their graduating class in high school.

Fun fact: If I did not receive this award, my parents would've been disappointed. (˶ˆᗜˆ˵)

My parents didn't even want me to pursue graduate studies. What were they expecting!? (•᷄ࡇ•᷅)

**1. Dr. Angelo Albanese Memorial Scholarship -** **Saint Michael's Catholic High School (2019)**

Awarded to a student who best demonstrates a mature approach to academics and a determination to succeed.
