---
title: "MATH 1AA3/1ZB3 Winter 2025"
toc: true
toc-depth: 3 # This sets the depth of headers included in the TOC
toc-location: left
toc-collapsible: true
---

Here are the tutorial notes written by Anna Ly for MATH 1AA3 (Calculus For Science II) and MATH 1ZB3 (Engineering Mathematics II) during the winter 2025 semester. Despite the different course codes, the course content is actually the same.

We followed Calculus by Steward et al. 9th edition. Tutorials focused on questions uploaded on [Childsmath](https://www.childsmath.ca/).

Some of the titles in the document do not necessarily match the titles listed here; this is because one section was earlier than the other, where I essentially skipped one week of content to match their due dates.

# Tutorial 1 (Assignment 1)

Chapters: 7.5 and 7.8

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut1.pdf)

# Tutorial 2 (Assignment 2)

Chapters: 11.1-11.2

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut2.pdf)

# Tutorial 3 (Assignment 3)

Chapters: 11.2-11.4

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut3.pdf)

# Tutorial 4 (Assignment 4)

Chapters: 11.5-11.8

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut4.pdf)

# Tutorial 5 (Test Review)

Here, questions were taken from the uploaded sample test.

[Worksheet & Solution (Sample 1)](MATH1AA3_1ZB3/calc2_tut5_part1.pdf)

[Worksheet & Solution (Sample 2)](MATH1AA3_1ZB3/calc2_tut5_part2.pdf)

# Tutorial 6 (Assignment 5)

Chapters: 11.9-11.11, and 8.2

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut6.pdf)

# Tutorial 7 (Assignment 6)

Chapters: 8.3, 9.1, 9.3, and 3.8

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut7.pdf)

# Tutorial 8 (Assignment 7)

Chapters: 9.5, 10.1, and 10.2

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut8.pdf)

# Tutorial 9 (Test Review)

A custom made exam review was created, going over most of the concepts needed for the term test.

[Beamer Slides](MATH1AA3_1ZB3/calc2_tut9.pdf)

# Tutorial 10 (Assignment 8)

Chapters: 10.2-10.4 and 14.1-14.3

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut10.pdf)

# Tutorial 11 (Assignment 9)

Chapters: 14.4-14.6

[Worksheet & Solution](MATH1AA3_1ZB3/calc2_tut11.pdf)

# Tutorial 12 (Exam Review)

Exam review focused on questions from uploaded sample tests.

[Worksheet & Solution (Sample 1)](MATH1AA3_1ZB3/calc2_tut12_sample1.pdf)

[Worksheet & Solution (Sample 2)](MATH1AA3_1ZB3/calc2_tut12_sample2.pdf)

[Beamer Slides (Few Relevant Equations/Theorems))](MATH1AA3_1ZB3/calc2_tut12_slides.pdf)

[Additional Practice Problems](MATH1AA3_1ZB3/calc2_tut12_additional.pdf)
