---
title: "About"
toc: true
toc-depth: 3 # This sets the depth of headers included in the TOC
toc-location: left
toc-collapsible: true
---

## Brief Introduction

My name is Anna Ly. I completed a [Master of Science in Statistics at McMaster University](http://hdl.handle.net/11375/32609), and prior to that I finished my undergraduate studies at the University of Toronto.

I'm a proud R programmer and [lme4](https://github.com/lme4/lme4) contributor.

I will be a lecturer at UTM for STA380 during the winter 2026 semester.

## Statistical Interests

I've recently become interested in pursuing topics in [statistical decision theory.](https://en.wikipedia.org/wiki/Decision_theory)

While pursuing graduate coursework, I developed an interest in the philosophical foundations of statistics. I am curious about how models function, why certain models or loss functions are preferred, and what criteria best measure utility, accuracy, and correctness in statistical practice.

This curiosity naturally led me to the common debate on interpreting probability: frequentist versus Bayesian. After exploring both perspectives, I side with the Bayesians.

I probably should have applied to Duke University, but to be honest I'm not fond of the United States of America in its current state. In the meantime, you should all [read this beautiful article.](https://sites.astro.caltech.edu/~george/aybi199/Lavine_whatisbayes.pdf)

## Where to Contact Me

The easiest way to reach me is through [Linkedin](https://www.linkedin.com/in/anna-ly-statistics-specialist/). I try to not be active on other social media platforms so I have more time... for research.

## Other Socials

If you try to search for my name, you'll have a rough time finding me. There's even another "Anna Ly" in my extended family... There were multiple Anna Ly's at the University of Toronto. Sometimes students would email the incorrect one and be upset that I didn't respond to their email. Anyways, I could vent about this all day. Here are my actual profiles:

[Github](https://github.com/annahuynhly) \| [Linkedin](https://www.linkedin.com/in/anna-ly-statistics-specialist/) \| [Google Scholar](https://scholar.google.com/citations?user=9w41oS8AAAAJ&hl=en) \| [Stackoverflow](https://stackoverflow.com/users/20815709/annahuynhly) \| [Reddit](https://www.reddit.com/user/annahuynhly/) \| [Medium](https://medium.com/@AnnaLyStats) (personal blog)

I am not active on Reddit. If you want to reach me, please DM me on Linkedin!

It is a common misconception that "Huynh" is my middle name. I have no middle name; it's my mom's last name.

## My Story

Since childhood, I have always been interested in probability and data visualization. I vividly recall the excitement of using crayons to colour bar plots, and that is when I knew statistics and I were a dynamic duo.

I also challenged my family's love for lotteries. Even back then, I had a sense of the gambler's fallacy and understood that casinos were not in the business of giving money away, but I could not prove it.

As an undergraduate student, I have received the privilege to be a teaching assistant for an introductory probability course. I shared how to compute probabilities and expected values of winning a Lotto 649 jackpot. Unfortunately, I still can't convince my father. :)

I love studying statistics because it allows me to comprehend the results of many studies without being an expert! Unlike previous generations, we live in a world where data and information are easily accessible, yet opinions formed without statistical evidence prevail. Conversely, I shape my perspectives similarly to a Bayesian model: I maintain prior beliefs but am always eager to adapt and refine them in the face of compelling evidence.

I am passionate about teaching statistics because I recognize the importance of a supportive teaching assistant. I've always been inspired by those who guide their students with understanding and without judgment. I am deeply grateful for the effective educators who have positively influenced my academic journey.

Some of you may wonder why I decided to pursue McMaster for graduate school instead of UofT, or a more prestigious school. I was actually born at the McMaster Children's Hospital. I knew from the womb that I needed to return to my birth of origin. I wanted to return so quickly I visited during my teenage years and was locked up in the mental health ward. More importantly, I wanted to have an [academically pure bloodline](https://link.springer.com/article/10.1007/s12564-015-9391-8).

## Fun Facts About Me

In this section you'll learn that I have interests outside of studying and teaching statistics. (The horror, I know.)

-   I grew up in Niagara Falls, Canada. From my parent's house, it takes only 45 minutes to walk to the falls. People say I'm lucky to have easy access to the magnificent falls but I've spent more time looking at that waterfall than studying statistics; it's become an eyesore to me.

-   I personally identify as Vietnamese Canadian as its the language my parents speak at home, although my ethnic background is complicated (and I'd rather not elaborate). I do not speak Vietnamese. Growing up, my parents were often working multiple jobs, so I learned the English language and communication through television.

-   I identify as a first-generation university student. Due to war, my parents did not even attend high school. I am the first person on my entire father's side of the family with a graduate degree.

-   I used to doodle all of the time; I hope to get back to drawing.

-   I have a very modest Pokemon card collection. (I don't play modern Pokemon though).

-   I love Mega Man, specifically the Battle Network and Zero series. In an alternative timeline where I didn't go to school, I'd be interested in becoming a Mega man speed-runner.

-   I have followed a strict plant-based diet since 2019.

-   My favourite youtubers are [Catherine Klein](https://www.youtube.com/@CatherineKlein94/videos) and [Lifting Vegan Logic](https://www.youtube.com/@LiftingVeganLogic/videos).
